### ISSUE TITLE
Range "tokens" that can be added and checked ad-hoc

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#1]
We've had a number of requests to be able to do range band checks from a variety of places (think mines, objectives, non-leader miniatures). We might want to consider a "range" token that allows spawning and checking range from an arbitrary location.

**Comment by tieren31** [comment]
Added range bubbles to condition, objective, mines and smoke tokens.

**Comment by matanlurey** [comment]
Thanks!
