### ISSUE TITLE
Consider spawning configurations on long range side

### ISSUE THREAD

**Issue by madmanrambler** [swlegion/tts#100]
Currently, Deathtrooper configuration as well as Pathfinder and Jyn configuration options spawn with their short range configurations as the default. Suggest looking into alternate options, either spawning them at long range (their more used side) as the default, or giving players the option to choose which spawn they prefer.

**Comment by matanlurey** [comment]
I'm closing this as infeasible, there isn't fine-grained enough control currently to do this in the mod.
