### ISSUE TITLE
Some Imperial models have a T-21 instead of the correct weapon

### ISSUE THREAD

**Issue by NocturnalLoner** [swlegion/tts#107]
Some Imperial minis incorrectly have the T-21 weapon for their heavy weapon mini or on their unit model. The following are examples of such;

Scout Trooper sniper rifle heavy weapons models have a scoped T-21 instead of a scoped DLT-19 variant.

Death Troopers' DLT-19D heavy weapon mini is carrying a T-21 instead of a DLT-19D.

The TX-225 GAVw Occupier Combat Assault Tank has a T-21 on its pintle mount instead of a DLT-19 or an RT-97C.

**Comment by nashjaee** [comment]
Thanks for the list! I can work on getting these updated.

**Comment by matanlurey** [comment]
@nashjaee: Any status?

**Comment by matanlurey** [comment]
Actually, this looks plausibly fixed, right?

![image](https://user-images.githubusercontent.com/168174/70762494-94665d80-1d05-11ea-9104-571634c5f366.png)

@nashjaee feel free to close if complete.

**Comment by nashjaee** [comment]
I've acquired the appropriate weapon models. Still need to put them onto the unit models. I should have time this weekend to get it done.

Yeah, the stormtrooper weapons are correct now, but we still need to update Deathtroopers, Imperial Sniper, and Imperial tank.
