### ISSUE TITLE
Many cards are incomplete, blurry, or not updated for errata

### ISSUE THREAD

**Issue by NocturnalLoner** [swlegion/tts#108]
While a rather low priority, there are several cards of various types in the mod that are either incomplete (missing images for example), are outdated and lack released and known errata on them, or are blurry to the point that text had to be superimposed on them for them to be functional in the mod. I have compiled a list of all reasonable instances of this I could find in the mod's current (as of typing this) build. I understand that some of these cards have no current released high quality picture available due to not being officially released. At the very least, this request documents what cards will need replacing or altering in the future if the cards cannot be updated currently.

Cards requiring errata corrections/new images for the errata'ed versions:

DH-447 and DLT-19X Sniper Rifle heavy weapon upgrades
1.4D Laser Cannon Team unit card
T-7 Ion Snowtrooper heavy weapon upgrade
E-Web Heavy Blaster Team unit card
T-47 Airspeeder unit card
Force Choke and Battle Meditation force upgrades
Long Range Comms upgrade
Coordinated Fire command card
Limited Visibility condition card

The next following section will list cards that are either blurry or incomplete and be split by each faction.

Generic/Shared cards:

Strict Orders command upgrade
Hope and Fear force upgrades
Endurance and Offensive Push training upgrades
Integrated Comms Antenna comm upgrade

Rebel Alliance:

C-3PO unit card
Tauntaun Riders unit card
X-34 Landspeeder unit card
Ryder Azadi pilot upgrade
A-300 Gunner hardpoint upgrade (X-34 Landspeeder)
The A-300 Short Range Config (Pathfinders)
The Darksaber Config (Sabine Wren)

Galactic Empire:

Darth Vader Operative unit card
Shoretroopers unit card
DF-90 Mortar Trooper unit card
Dewback Rider unit card
TX-225 GAVw Occupier Combat Assault Tank unit card - *Note: The Occupier card also lists an incorrect movement speed of 2 instead of its actual movement speed of 1*
First Sergeant Arbmab pilot upgrade
Shoretrooper personnel upgrade
T-21B Trooper heavy weapon upgrade (Shoretroopers)
RT-97 Blaster Rifle, T-21 Blaster Rifle, and CR-24 Flame Rifle hardpoint upgrades (Dewback Rider)
E-11D Grenade Launcher Config (Death Troopers)

Grand Army of the Republic:

Clone Captain Rex unit card
Phase II Clone Troopers unit card
TX-130 Saber Class Fighter Tank unit card
Phase II Clone Trooper personnel upgrade
Aayla Secura pilot upgrade

CIS/Separatists:

Count Dooku unit card
B2 Super Battle Droid unit card
AAT Trade Federation Battle Tank unit card
B2 Super Battle Droid personnel upgrade
T-series Tactical Droid Pilot pilot upgrade

**Comment by matanlurey** [comment]
I will work on getting some better images in the mod (not handling erratas currently).

**Comment by matanlurey** [comment]
Staged card sets:

![tons-of-upgrades](https://user-images.githubusercontent.com/168174/70833851-a3a0e600-1dad-11ea-9fc8-edaaf7c68f54.png)

![sf-upgrades-front](https://user-images.githubusercontent.com/168174/70833855-a7346d00-1dad-11ea-8c0f-09b85d6bebe7.png)

![sf-upgrades-back](https://user-images.githubusercontent.com/168174/70833860-a996c700-1dad-11ea-8be8-4b6d77747ce7.png)

**Comment by matanlurey** [comment]
Lots of these went in. I'm still missing pictures for some cards.

**Comment by TedSoper** [comment]
Is there an updated list of needed cards? I could look at sourcing them.

**Comment by matanlurey** [comment]
Good question. I don't think there is :(

If someone has a chance, we should open up some more specific bugs.
