### ISSUE TITLE
Strike Teams heavy weapon mini gets switched out when swapping sides

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#111]
**Describe the bug**
Reported on discord (I believe a number of times) so this is a copy/paste of the last mention:
"So I've spawned 3 proton strike teams for a game and the sabs decided to take the day off, got 2 normal gals in each squad instead..."

**To Reproduce**

**Expected behavior**

**Screenshots**

![](https://cdn.discordapp.com/attachments/388041509041340446/643172966976454666/unknown.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux]

**Additional context**

**Comment by matanlurey** [comment]
Duplicate of #13
