### ISSUE TITLE
Add Skirmish Format

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#113]
FFG have released an official Skirmish format played on a 3x3 battlefield with 12 Battle Cards specific for this format.

https://images-cdn.fantasyflightgames.com/filer_public/52/ac/52ac3c8e-f20c-44c3-977a-f49a0d0eebb2/star_wars_legion_skirmish.pdf

We need maps, battle cards, deployment zones, and objective tokens. I would suggest a new game controller is created to handle this format.

**Comment by matanlurey** [comment]
We don't have a formal support yet, but 3x3 featured maps were added.

**Comment by dicewrench** [comment]
Round Deployment Projectors (for Faceoff Deployment) are now in the assets repo and bundles were shared on the discord.
