### ISSUE TITLE
Z6 and acm trooper upgrades to add in

### ISSUE THREAD

**Issue by madmanrambler** [swlegion/tts#117]
Z6 and acm troopers have been fully revealed and are ready to be added to the mod. Z6 card https://cdn.discordapp.com/attachments/560928629891137556/651206038309044225/image0.jpg
And acm trooper card
https://cdn.discordapp.com/attachments/349001242489520129/651205418412015647/B2-ACM.jpg

**Comment by matanlurey** [comment]
![clones-corps-2-heavies](https://user-images.githubusercontent.com/168174/70761975-db535380-1d03-11ea-8ce0-ce6906f8db15.png)

Prepared the 2x2 upload for TTS. I'll hold this until #119 is merged.

**Comment by matanlurey** [comment]
We actually will need the models first. Unassigning until those are in

**Comment by matanlurey** [comment]
Actually I can make incremental progress, so I'll do that!

**Comment by matanlurey** [comment]
Fixed!
