### ISSUE TITLE
Command token code needs clean-up

### ISSUE THREAD

**Issue by nashjaee** [swlegion/tts#123]
**Describe the bug**
There is duplicate code related to command tokens. Tokens programmatically generated by the list builder have a different source of truth than the tokens that users can pull from the infinite stacks on the side of the board. This is a problem because code needs to be copy-pasted in up to 3 places to ensure changes are propagated everywhere.

The list builder uses blockrectangle.a57c41.lua.
The manual tokens use the .lua files in "mod/src/blue_command tokens/" and "mod/src/rebel_command_tokens/"

**To Reproduce**
1. Make changes to blockrectangle.a57c41.lua, but nowhere else
2. Save, embed, and open in TTS
3. Spawn a list
4. Manually pull a corresponding token from the infinite stacks
5. Activate a unit with the various tokens and notice that the list builder's command tokens have the changes, but the manual ones don't.

**Expected behavior**
Command tokens should behave the same regardless of how they are generated.

**Comment by nashjaee** [comment]
If the tokens in the infinite stacks can draw their code from blockrectangle.lua, I think we can actually delete all those .lua scripts in the directories mentioned above. They appear to be superfluous.

**Comment by nashjaee** [comment]
If it's not possible to get the tokens to essentially generate their code on-the-fly as they're pulled from the infinite stack, we could consider removing the infinite stacks and replacing them with a tray of buttons to generate the tokens that users may need at any point.

I imagine this is a rare use-case at any rate.

**Comment by aldaranmoses** [comment]
The Atom TTS Package has the ability to #include files, basically inserts the contents of the file at that point in the script, thus for the token script it would simply contain "#include name_of_script_file" and then we have the single source of truth in "name_of_script_file". However, this means changing our current workflow.

**Comment by aldaranmoses** [comment]
Eureka! 
We add a new button to the command tray and a infinite bag of “blank” order tokens (replaces the existing bags). Place a blank token on the rank slot you require and clicking the button will set up the token with the same script from blue rectangle and assign the token data.

**Comment by aldaranmoses** [comment]
This doesn’t work as it needs a unit name to determine some data. 

Plan B: “blank” order token with a single button, place the token on the required unit card and press the button, the token will be set up for that unit.

**Comment by aldaranmoses** [comment]
Plan C: discovered there is a Player.getSelectedObjects() method, I am using this to enable the assigning of "blank" order tokens. The user selects the "blank" token and the unit leader mini they wish to assign to the token, pressing the button on the "blank" token does the assignment. This method ensures we have the unit name inserted into the token.

This will partially help with those units that can be designated commander or operative at deployment, except the unit data doesn't handle the alternative ranks.
