### ISSUE TITLE
Adding in Cassian and Iden

### ISSUE THREAD

**Issue by madmanrambler** [swlegion/tts#126]
2 new commanders have been revealed, Cassian and Iden. Both are somewhat complex, as they have an option to be deployed as an operative rather then a commander. There are obvious work arounds but we might want to look in on how to most easily make sure this mechanic transitions smoothly for the characters.

Cassian's unit card-
https://tabletopadmiral.com/static/legion/images/Cassian%20Andor%20and%20K-2SO/Cassian%20Andor.png
(card might be difficult to read, it is 90 points and his keywords are Covert Ops [before you deploy you may change your rank to Operative and gain infiltrate] danger sense 3, tactical 1, loadout [before you deploy you may exchange any upgrade cards you have equipped with set aside upgrade cards] and Marksman [after attacking you may spend an aim token to improve attack die results]
Cassian's 1 pip-
https://tabletopadmiral.com/static/legion/images/Cassian%20Andor%20and%20K-2SO/Crack%20Shot.png
Cassian's rifle (will need to be double sided at one point to add in the other config option)-
https://tabletopadmiral.com/static/legion/images/Cassian%20Andor%20and%20K-2SO/A200-CFE%20Sniper%20Config.png
(because that one is particularly blurry its agreed to be an armament upgrade for 10 points with range 1-infinite, red black attack dice, cumbersome, high velocity, pierce 1, reconfigure.)

Iden Versio's unit card-
https://tabletopadmiral.com/static/legion/images/Iden%20Versio%20and%20ID10/Iden%20Versio.png
(100 points, keywords are quick thinking, covert ops, loadout, marksman, nimble)
Iden's 1 pip-
https://tabletopadmiral.com/static/legion/images/Iden%20Versio%20and%20ID10/Pulse%20Scan.png
Iden's rifle
(card is not currently cropped, stats are 15 points for an armament that is range 1-infinite with Black Black as the attack dice, pierce 1 and high velocity)

**Comment by nashjaee** [comment]
Copying over my idea from the discord:

"what about spawning a couple buttons below the unit card? When you go to deploy the unit, you click which unit rank you want. The buttons then disappear and the correct token spawns in the token stack?"

Loadout will also need a solution...

**Comment by aldaranmoses** [comment]
![SWL60_Card-Upgrade-Armament--Idens_DLT-20A_Rifle](https://user-images.githubusercontent.com/53875637/73642341-d8c10a80-4671-11ea-88a6-4befbde9138d.jpg)


![SWL59_Card-Upgrade-Armament--A280-CFE_Sniper_Config](https://user-images.githubusercontent.com/53875637/73642437-fdb57d80-4671-11ea-9b33-8fed34af2662.jpg)

**Comment by matanlurey** [comment]
I added the cards we have - it is not playable yet obviously.
