### ISSUE TITLE
Add revealed TX-130 Saber-Class Fighter Tank Upgrades

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#128]
For the TX-130 Saber-Class Fighter Tank  the following upgrades have been revealed "TX-130 Beam Cannon Turret" & "Veteran Clone Pilot".

I have created some stand-ins for the mod.

![SWL-Card-Upgrade-Hardpoint-TX-130-Beam-Cannon-Turret](https://user-images.githubusercontent.com/53875637/73343801-7cc94100-4281-11ea-8f9c-b841cafed571.png)
![SWL-Card-Upgrade-Pilot-Veteran-Clone-Pilot](https://user-images.githubusercontent.com/53875637/73343808-805cc800-4281-11ea-9b26-4ce43bbba7ad.png)

**Comment by aldaranmoses** [comment]
The stand ins have been replaced with official released images.

**Comment by aldaranmoses** [comment]
2 more revealed upgrades; TX-130 Twin Laser Turret & Plo Koon

![SWL63-Card-Upgrade-Hardpoint--TX-130_Twin_Laser_Turret](https://user-images.githubusercontent.com/53875637/73682211-34b28000-46c0-11ea-8814-ef86a6524c3e.png)
![SWL63-Card-Upgrade-Pilot--Plo-Koon](https://user-images.githubusercontent.com/53875637/73682212-34b28000-46c0-11ea-8418-460221e3e5e0.png)

**Comment by matanlurey** [comment]
Fixed!
