### ISSUE TITLE
Add revealed AAT Tank Upgrades

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#132]
For the AAT Trade Federation Battle Tank add the revealed Pilot "Lok Durd" and add the ordnance upgrade menu.

![SWL64-Card-Upgrade-Pilot-Lok_Durd](https://user-images.githubusercontent.com/53875637/73589458-e9894900-44d6-11ea-9885-619e95456934.jpg)

**Comment by matanlurey** [comment]
Fixed!
