### ISSUE TITLE
GAR: Add Padme Amidale

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#137]
https://store.us.asmodee.com/catalogue/sw-legion-padme-amidale-operative_2567/

![Padme Amiddale](https://user-images.githubusercontent.com/168174/74266167-b013c300-4cb8-11ea-8f94-b602b2982a1e.png)

**Comment by matanlurey** [comment]
Upgades:
https://www.fantasyflightgames.com/en/news/2020/2/11/special-agents/

**Comment by aldaranmoses** [comment]
AGGRESSIVE NEGOTIATIONS (2 pips)
Padmé Amidala and 1 trooper 
When Padmé Amidala issues an order to a trooper unit, that unit can either perform a speed-1 move or gain an Aim, Dodge or Surge token
