### ISSUE TITLE
CIS: Add Cad Bane

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#139]
https://store.us.asmodee.com/catalogue/sw-legion-cad-bane-operative-expansion_2568/

![Cad Bane](https://user-images.githubusercontent.com/168174/74266302-eea97d80-4cb8-11ea-8293-1b2fa27d3aed.png)

**Comment by matanlurey** [comment]
Upgades:
https://www.fantasyflightgames.com/en/news/2020/2/11/special-agents/

**Comment by aldaranmoses** [comment]
AGGRESSIVE NEGOTIATIONS (2 pips)
Padmé Amidala and 1 trooper 
When Padmé Amidala issues an order to a trooper unit, that unit can either perform a speed-1 move or gain an Aim, Dodge or Surge token


I’M YOUR WORST NIGHTMARE (1 pip)
Cad Bane 
Cad Bane gains Uncanny Luck 2. During his activation, Cad Bane can perform up to 2 Attack actions.
