### ISSUE TITLE
Range labels mistakenly use defeated models

### ISSUE THREAD

**Issue by nashjaee** [swlegion/tts#144]
The scripted range labels can sometimes be incorrect because they take into account defeated models within a unit that are not on the board.
![wrong_range](https://user-images.githubusercontent.com/8440699/75096207-2da9bf80-5552-11ea-8e83-0c3f42008240.jpg)

**Comment by nashjaee** [comment]
Seems that this can be fixed by only measuring to/from models inside the scripting zone?

**Comment by matanlurey** [comment]
Seems reasonable!

**Comment by matanlurey** [comment]
Did a little research. 

The code is `blockrectangle.a57c41.lua`, and currently checks `battlefieldZone`:

```lua
battlefieldZone = getObjectFromGUID(Global.getVar("battlefieldZoneGUID"))
```

... which is this big center zone, and seems "right": 
![Battlefield Zone GUID](https://user-images.githubusercontent.com/168174/75099178-7d4cb300-5573-11ea-99c4-c48b0cea175d.png)

... it for sure is buggy though. Here you can see the bug with the zone shown:

![Bug](https://user-images.githubusercontent.com/168174/75099214-e46a6780-5573-11ea-97a1-4abe628ed68f.png)

... which leads me to believe the range finder, not the targeting code, is not using the zone.

**Comment by matanlurey** [comment]
Ah, I see the bug. We get the enemy "leader", and all of its minis:

```lua
    for _, leader in pairs(enemyLeaders) do
        local enemyID = leader.getVar("unitID")
        local enemyMinis = leader.getTable("miniGUIDs")
        highlightUnit(enemyMinis,highlightTints[enemyID])
    end
```

... there is no filter/exclusion of minis not inside the zone. Investigating a simple fix.

**Comment by matanlurey** [comment]
Ok, looks pretty easy to fix:

![Fix](https://user-images.githubusercontent.com/168174/75099567-02d26200-5578-11ea-9171-4d0fbcca0ec7.png)

```lua
function isMiniOnTable(mini, allUnits)
  for _, check in pairs(allUnits) do
    if check == mini then
      return true
    end
  end
  return false
end
```

... and using it:

```lua
function createRangeButton(leaderObj)
    local selectedUnitObjUnitName = selectedUnitObj.getVar("unitName")
    local allUnitsOnTable = battlefieldZone.getObjects()
    local enemyLeaderUnitName = leaderObj.getVar("unitName")
    local enemyMinis = leaderObj.getTable("miniGUIDs")
    local lowestDistance = 99

    for k, guidEntry in pairs(enemyMinis) do
        local obj = getObjectFromGUID(guidEntry)

        if obj != nil and isMiniOnTable(obj, allUnitsOnTable) then
            distance = getDistance(selectedUnitObj, obj)
            if distance < lowestDistance then
                lowestDistance = distance
            end
        end
    end

    lowestDistance = lowestDistance - templateInfo.baseRadius[unitInfo[enemyLeaderUnitName].baseSize]/2 - templateInfo.baseRadius[unitInfo[selectedUnitObjUnitName].baseSize]/2

    finalRange = math.ceil(lowestDistance/6)
    if finalRange > 4 then
        finalRange = ">4"
    end

    local buttonHeight = unitInfo[enemyLeaderUnitName].buttonHeight
    local data = {click_function = "dud", function_owner = self, label = finalRange, position = {0, buttonHeight, 0}, rotation = {0, 180, 0}, scale = {0.5, 0.5, 0.5}, width = 900, height = 700, font_size = 500, color = {1, 1, 0, 1}, font_color = {0, 0, 0, 1}}

    leaderObj.createButton(data)
end
```

**Comment by matanlurey** [comment]
![Fixed](https://user-images.githubusercontent.com/168174/75099608-707e8e00-5578-11ea-932e-44003da9b150.png)
