### ISSUE TITLE
Movement tool in VR breaks apart when moving up

### ISSUE THREAD

**Issue by scooper4711** [swlegion/tts#158]
**Describe the bug**
When playing in VR, grabbing the movement tool to adjust it, it breaks apart at the hinge. 

**To Reproduce**
1. Activate a unit
2. Click on 'move'
3. Grab the movement tool as if to adjust it
4. The tool instantly breaks apart at the joint

**Expected behavior**
You are able to move the tool

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows, Oculus Quest and RiftCat
 - Version ??

**Additional context**
I believe that this can be fixed with modeling. Put a bottom on the joint to prevent them breaking apart.

**Comment by scooper4711** [comment]
Looks like today’s update to TTS may allow for an easy fix. 
@everyone Update v12.3 Attach Tool, Server Browser & Search Improvements, and much more! https://steamcommunity.com/games/TabletopSimulator/partnerevents/view/2077789829878273122

The ability to attach two objects.

**Comment by matanlurey** [comment]
I think it is unlikely anybody on the core team is going to invest time into fixing VR support.

We are happy to see contributions if you would know how to do it.
