### ISSUE TITLE
Range Ruler tool

### ISSUE THREAD

**Issue by Col-Ki** [swlegion/tts#177]
In order to make measuring ranges from arbitrary points faster, have a token available with permanently attached range bands from its centre.

**Comment by polepage** [comment]
While I totale second this request, since range is 6" per band it's extremely easy with tab+drag to get the range between two things on the board.

**Comment by matanlurey** [comment]
We decided against this feature and are going to focus on making range rulers accessible from any mini: https://github.com/swlegion/tts/issues/322
