### ISSUE TITLE
Mechanized Incursion when in command hand appears black compared to other cards

### ISSUE THREAD

**Issue by madmanrambler** [swlegion/tts#186]
While in the command hand to all viewers Mechanized incursion appears as a black card rather then a command card.

**Comment by nashjaee** [comment]
It was reported on the discorded that this issue still exists (also for the GAR 1-pip, Synchronized Offensive). Possibly the JSON file was overwritten during a merge.

**Comment by bgmoore30** [comment]
This was resolved in one of the last updates
