### ISSUE TITLE
Custom Map Texture Function no longer working

### ISSUE THREAD

**Issue by Nerfley** [swlegion/tts#190]
In one of the map submenus there is an option to add your own texture to the game mat. This is done through a dialogue box that is attached to a mini that is spawned when you select the custom texture option. That mini's source links are no longer functioning, which deletes the entire mini when the pop up custom box is closed, preventing a user from adding a custom texture to the game mat. This also prevents the map from setting a default tint to the minis bases, leaving them bright white.

The specific menu navigation to reach that menu is:
Maps > Next > Custom Maps > Custom Texture

The old mini was an old Luke Skywalker commander model, and I believe it was hosted in another location that is no longer available. I believe replacing the model that is spawned may fix the issue, but I am not sure.

**Comment by Nerfley** [comment]
Further exploration has revealed that you can still change the mat texture as long as the pop up custom model window is not closed. Bases are still unable to be tinted, and the process remains not user friendly.

**Comment by matanlurey** [comment]
Fixed at HEAD.
