### ISSUE TITLE
Objective interactivity breaks when loading saved game

### ISSUE THREAD

**Issue by nashjaee** [swlegion/tts#191]
Reported by users on the discord server.

When loading a saved game that was using e.g., Payload as the objective, the buttons that allow moving or measuring range from the objective do not appear. Same thing occurs with mines, etc.

1. Begin a game using Payload
2. Save game and exit
3. Load the saved game
4. Notice buttons for interacting with objective tokens do not appear

**Comment by matanlurey** [comment]
I _think_ this is no longer the case since a recent~ish refactor.

I can at least confirm loading a saved game with a payload objective persists the buttons.
