### ISSUE TITLE
Remove Tokens button crashes game on Mac

### ISSUE THREAD

**Issue by brandonlee781** [swlegion/tts#192]
**Describe the bug**
Running TTS v 12.4.3 and the latest version of the Legion mod. Had set up the tutorial game and moved some pieces around. When I click the Remove Tokens button TTS crashes to desktop.

**To Reproduce**
Not really sure if any of this is helpful or usable. But if you load up this save file and click the Remove Token button the game crashes. Also included is the Mac crash log
[save_files.zip](https://github.com/swlegion/tts/files/5475952/save_files.zip)
Crash Log: https://pastebin.com/MdPTUGnB

**Expected behavior**
Game shouldn't crash

**Desktop (please complete the following information):**
Mac OSX 10.15.7

**Comment by matanlurey** [comment]
Thanks for the report. I haven't seen this reproduced since, and there have been many releases of both the mod and TTS since. Please re-open if you see this occur.
