### ISSUE TITLE
Range bubbles should stay in position even if a unit leader moves

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#2]
Currently the range bubbles when spawned stay in position. This causes users to have to close the range bubble and re-open it when moving the unit leader.

**Comment by aldaranmoses** [comment]
Do you mean "move the range bubble with the unit leader"?

**Comment by tieren31** [comment]
added feature that moves the range bubbles when the unit leader is picked up and move

**Comment by matanlurey** [comment]
Thanks!
