### ISSUE TITLE
Points updates to RRG 2.0

### ISSUE THREAD

**Issue by Longbombed** [swlegion/tts#224]
Found some points discrepancies from RRG 2.0

Imps:
 Shoretrooper personnel is 13 should be 9

Rebs:
Sabine's Dark Saber is 25 should be 15
Bistan is 32 should be 28
MPL-57 Ion Trooper (Reb Trooper Heavy) is 22 should 18
Rebel Veteran personnel is 12 should be 9

**Comment by matanlurey** [comment]
Thanks for the issue! 

Unfortunately, we don't accept bugs related to the point costs in the list builder:
https://github.com/swlegion/tts/wiki/FAQ#i-am-able-to-create-a-list-that-is-not-legal
