### ISSUE TITLE
[Possible fix on beta branch] Mod doesn't spawn minis

### ISSUE THREAD

**Issue by timesparrow** [swlegion/tts#227]
When trying to load or create an army, the cards and tokens appear but the minis don't. When checking the scripting area, tabs have appeared for each mini. After clicking the spawn minis button, the entire game board can't be interacted with. Items can be drag highlighted but not moved nor can their context menus be accessed.

When loading a featured map, the game controller throws an error(see below). The map's data pack has spawned and can be then loaded using the manual load map button.

Error in Script(GAME CONTROLLER - 623b03):chunk_3:(96,4-95):attempt to index a nil value

**Comment by nashjaee** [comment]
Thanks for reporting the issue. Tabletop Simulator released an update todah that broke mini spawning in our mod. Other mods are reportedly affected as well.

We are waiting to see if their hot fix that is currently in the works fixes it before investigating further.

**Comment by timesparrow** [comment]
Thank you for a quick reply. The mod was great before today and thanks for all your work.

**Comment by matanlurey** [comment]
Posting what I've seen elsewhere:

> The latest release of Tabletop Simulator had several system-breaking bugs. Berserk is aware of the problems and is burning many flavours of midnight oils and both ends of several candles to work out the kinks.
>
> In order to let folks get on with their gaming while they pick through the debris, Berserk has placed the previous version of TTS under the "Public Beta" branch.
>
> To access this, go to your steam library, right click on Tabletop Simulator and click Properties. Go to the Betas tab and select the "public_beta" option. TTS will take a moment to re-download and you should be good to go.
>
> A followup announcement will be made when the main branch of TTS is fixed.

**Comment by matanlurey** [comment]
A fix has been uploaded to https://go.swlegion.dev/beta.
