### ISSUE TITLE
Simplify unitInfo.*

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#237]
TODO:

* [ ] Find a permanent solution to `.buttonHeight`.
* [x] Remove `.fixedX` assignments (make it a computed state instead).
* [ ] Remove `.fixedX` entirely (it still exists/is computed in some intermediate structures)
* [x] Remove `.squadStatus` (make it a computed state instead).
* [ ] Simplify `.commandType` (as `.rank`): this is a lot of work as it is used/referenced all over.
* [x] Remove unused properties in `unitInfo`.

... it might be worth figuring out how to merge `unitInfo` with `cardInfo` and `miniInfo` (long-term work): #247.

---

Specifically:

* Can we store all units as a list instead of a nested associative array/dictionary?
* We don't need `.buttonHeight`, it looks like we can just hard-coded this as 4 or 5.
* We don't need `.fixedArc` or `.fixedMove`; any non-`small` base is `true`, everything else is `false`.
* We might be able to set `.squadStatus` "live", i.e. when the unit is spawned, instead of based on the unit type.
* We should consider simplifying `.commandType` (as `.rank`) and not have faction-specific command types.

**Comment by nashjaee** [comment]
Another question:
Is there a good reason we maintain `unitInfo` and `cardInfo.unitCards` as separate tables? Can we merge this info?

**Comment by nashjaee** [comment]
> Specifically:
> 
> * Can we store all units as a list instead of a nested associative array/dictionary?
I think we need an associative array. I don't know how else we can support a list importer from external list builders (without looping through the entire table and checking parameters).
> * We don't need `.buttonHeight`, it looks like we can just hard-coded this as 4 or 5.
We should test this first. We have a wide range of heights across our models, and I wonder if a constant height for units such as Landspeeders vs Airspeeders would work?
> * We don't need `.fixedArc` or `.fixedMove`; any non-`small` base is `true`, everything else is `false`.
Agreed
> * We might be able to set `.squadStatus` "live", i.e. when the unit is spawned, instead of based on the unit type.
Agreed. We have to do this already with R2, right?
> * We should consider simplifying `.commandType` (as `.rank`) and not have faction-specific command types.
Agreed

**Comment by matanlurey** [comment]
Some updates:

* Hardcoding (or dynamically computing) `buttonHeight` seems like a no-go. We'll need to have model height encoded.
* I was able to remove some unnecessary/unused code, though.
* Going to look at `.fixed{Arc|Move}` and `.squadStatus` next.

**Comment by matanlurey** [comment]
Ok I was able to make partial progress and remove some (but not all) of these properties (see above).

**Comment by matanlurey** [comment]
Unassigning as I'm not working on the remaining items right now.

**Comment by matanlurey** [comment]
Closing for now, as I think the new Card DB does most of what we want. Will open future issues as necessary.
