### ISSUE TITLE
Simplify `cardInfo.upgradeCards.*`

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#241]
Specifically:

1. Can we remove `.varName`? Is this even used? Can we get this association another way?
2. Can we store all upgrade cards as a list instead of a nested associative dictionary/array?

**Comment by nashjaee** [comment]
We do use `varName` when loading a list. The loader has to check the table to see if there is a mini associated with the upgrade. If not for that use-case, we could just spawn upgrade cards based on a simple string stored in the datadisk.

Maybe we can refactor the keys in `cardInfo.upgradeCards` to match the recommendations in [our list importer wiki](https://github.com/swlegion/tts/wiki/List-Importer)?

**Comment by matanlurey** [comment]
Closing for now, as I think the new Card DB does most of what we want. Will open future issues as necessary.
