### ISSUE TITLE
Cannot start game minis do not load

### ISSUE THREAD

**Issue by Wataru2001** [swlegion/tts#252]
> NOTE: We will close all bugs related to the point costs in the list builder:
>
> https://github.com/swlegion/tts/wiki/FAQ#i-am-able-to-create-a-list-that-is-not-legal

**Describe the bug**
When we started a game and loaded armies (once with a data card, once by manually inputting army info and hit Spawn Minis) either no minis load or they appear to load below the table and quickly vanish through the surface with gravity.  Also, when creating an army, we could not move tokens or push buttons (such as choose map). 

**To Reproduce**
1. Load or Create Army
2. Click Spawn MInis (if army was created)

**Expected behavior**
No minis appear on the board and we cannot interact with many of the buttons, such as the map selection or the Game Setup

**Screenshots**

**Desktop (please complete the following information):**
 - OS: One on Windows OS, one on Mac OS

**Additional context**
:*(

**Comment by matanlurey** [comment]
You are using a version of the mod that is no longer supported.

The latest version of the mod is here: https://go.swlegion.dev/mod
