### ISSUE TITLE
DB Refactor: Known Issues

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#296]
Here are bugs I see at a first glance for https://github.com/swlegion/tts/pull/274:

## General

- [x] Upgrade Next/Previous Buttons do not change the listed upgrades
- [x] Command Card pips all cause an "index a nil value" error to be thrown (if any cmd or operative was added)
- [x] A commander/operative that is added and removed is not cleared in list building logic (see attached image)
- [x] Points seem to be super off across the board (didn't dig in too deep here)

## Republic

- [x] Operative > R2-D2: Shows a T-Series Tactical Droid Unit Card
- [x] Operative > R2-D2 > C-3PO: _Shows_ an EV-Series Medical Droid Upgrade Card
- [x] Operative > R2-D2 + C-3PO: _Spawns_ a Padme Unit Card w/ Imperial Comms Tech Upgrade Card
- [x] Support > AT-RT: Spawns the Rebel AT-RT Unit Card
- [x] Heavy: No unit cards show up at all (empty category)

## Separatist

- [x] Special Forces: Maul's Droids do not show up6
- [x] Special Forces: BX Strike Team has a blank label

## Imperials

- [x] Commander > Darth Vader: _Shows_ a T-Series Tactical Droid unit card, spawns the last correct card
- [x] Commander > Emperor Palpatine: _Shows_ a T-Series Tactical Droid unit card, spawns the last correct card
- [x] Operative > Darth Vader: Unexpected symbol near 'apprentice' error is thrown on spawn (seems to show up tho)
- [x] Support: Most (all?) of these units throw errors in console on spawn
- [x] Support > Speeder Bikes: Shows a T-Series Tactical Droid unit card, spawns the last correct card
- [x] Special Forces > Inferno Squad: Shows two Proton Charge Saboteur upgrades instead of Hask/Meeko
- [x] Heavy: Occupier unit is unlabeled in the list builder

## Rebels

- [x] Commander > Lando: Automatically spawns a HH-12 Stormtrooper upgrade (probably meant to be the flaw)
- [x] Support: AT-RT does not show up as an option
- [x] Special Forces > Clan Wren: Spawns two DLT-19x Sniper upgrades instead of Tristan/Ursa Wren

**Comment by nashjaee** [comment]
@matanlurey thanks for the reports. Can you explain this one a bit further? I'm not seeing any errors related to command cards:
"Command Card pips all cause an "index a nil value" error to be thrown"

**Comment by matanlurey** [comment]
Yup, I believe it occurs on adding any commander or operative - then I can't select command cards anymore.

**Comment by matanlurey** [comment]
![image](https://user-images.githubusercontent.com/168174/112775471-cfbb9700-8ff1-11eb-900f-512b9905f25b.png)

This is an example of the bug I got by adding a bunch of commanders/operatives, removing them clicking "1 Pips".

**Comment by matanlurey** [comment]
Downgrading to P2 since all the higher priority issues seem resolved. Here are the lower priority ones.

(Note: I didn't check anything related to command cards)

## General

- [ ] Importing list cartridges should probably fail gracefully if they are an older version, they crash now
- [ ] Force powers no longer seem filtered by alignment (Luke can take force choke, for example)
- [ ] All units w/ gear slot capable of taking Sabine and Rex-specific gear upgrades
- [ ] All units w/ comms slot capable of taking Linked Targeting Array, Command Control Array

## Republic

- [ ] Anakin's flaw does not appear nor automatically spawn
- [ ] Neither Echo nor Fives can be taken on a Corps unit

**Comment by nashjaee** [comment]
## General
- [ ] Comms Relay can be added to emplacement troopers
- [ ] Offensive Stance can be added to non-force users
- [ ] Seize the Initiative can be added to non-Commanders and non-Operatives

## Separatist
- [ ] Portable Scanner and Electrobinoculars can't be added to B1s
