### ISSUE TITLE
Range bubbles are "hard to see" from above

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#3]
... due to being a vertical strip. Can we make it more easy to see?

**Comment by nashjaee** [comment]
This one requires some care in implementation. An infinitely thin plane makes playability abundantly clear. If we do something like adding thickness to the range band lines then it becomes ambiguous where the delineation between ranges actually sits (which side of the thick line is the edge of the band?).

This is less of an issue if the scripted range labels become more reliable.
