### ISSUE TITLE
Document what terrain/assets not compatible with projected deployments

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#300]

**Comment by dicewrench** [comment]
**What's the Problem?**
As of TTS v13.0 importing any Custom Model using a .png texture causes TTS to render that Custom Model with an Unlit Cutout shader, which does not support Projectors.

This means any Custom Model with a .png texture won't work for Grid Projection or Legion's Custom Deployment Zone Projectors.

**How should you solve this in your maps?**
1. Try using a .jpg texture instead (this will not support transparency, and might make your model look ugly if its not designed for this).

2. Create a Custom AssetBundle for your terrain feature instead: https://kb.tabletopsimulator.com/custom-content/custom-assetbundle/

You can use a Standard Cutout Shader as your material, or write a custom shader that does not IgnoreProjectors.  This will require more GPU performance to draw, so don't make a map full of these things.  Look, I can't explain all of vidya game performance in a bullet point list, if I could do this stuff with a flowchart I'd replace myself with an AI and retire.

**Comment by matanlurey** [comment]
Moved into https://github.com/swlegion/tts/wiki/FAQ#what-terrain-objects-arent-fully-supported-by-the-mod and closed.
