### ISSUE TITLE
Army List Cards Overlay

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#39]
**Is your feature request related to a problem? Please describe.**
I hear people mentioning it's an effort to keep scrolling back to the cards on the table to check them, and personally agree.

**Describe the solution you'd like**
I am suggesting an overlay (UI) that can be toggled showing the cards along one side of the screen to minimize the the going back and forth when looking up info.

**Describe alternatives you've considered**
The user could set a camera position over the cards and use the keyboard shortcut to snap to the camera, but then still needs to scroll to another location on the table.

**Additional context**

**Comment by matanlurey** [comment]
This is a neat concept. So something like the table-top admiral "text view" of the army that can be shown in the corner of the screen?

**Comment by aldaranmoses** [comment]
I was thinking more an actual view of the cards so you could check how many dice needed or if the unit has surges, etc. I would say both players and it would display yours on the left and the opponents on the right. using toggle buttons to display or not.

**Comment by aldaranmoses** [comment]
This may be useful for the grey spectator player  and streamers too

**Comment by matanlurey** [comment]
![fz4tvzkbafn31](https://user-images.githubusercontent.com/168174/65263545-b6af5d00-dac1-11e9-87e0-3f603dcd25ba.jpg)

(From [Reddit](https://www.reddit.com/r/SWlegion/comments/d64bzr/i_designed_a_minilist_that_fits_in_a_standard/))

**Comment by matanlurey** [comment]
So I looked into this a little bit over the weekend.

I am not sure it is feasible to create anything too fancy - since TTS doesn't really allow any sort of custom painting or UI outside of the scope of what already exists.

We _could_ quite easily set text notes on the side of the screen (i.e. where the model sizes are currently listed for reference) - would that be enough? @aldaranmoses
