### ISSUE TITLE
Movement tools cause other miniatures to slide

### ISSUE THREAD

**Issue by Col-Ki** [swlegion/tts#45]
Movement tools often get under the bases of other minis on the table and cause them to slide out of position.

**Comment by matanlurey** [comment]
This is not an area where I have lot of expertise yet, so its possible this is fundamentally impossible to fix. Its also possible we could do something like lock all other models on the table when the ranger ruler is out.

I will ask @tieren31 what he thinks.

**Comment by Col-Ki** [comment]
Hi Mat - the lock idea is a good one. Perhaps triggered by the "end" action on a command token?

**Comment by matanlurey** [comment]
Makes sense to me!
