### ISSUE TITLE
VR support movement tool

### ISSUE THREAD

**Issue by g-doh** [swlegion/tts#47]
**Is your feature request related to a problem? Please describe.**
The movement tool is not working using VR. When you try to move the whole tool or just the part beyond the hinge then it comes apart and does not reacht the layout you might expect.

**Describe the solution you'd like**
Not sure what the best Sollutions could be.

**Comment by matanlurey** [comment]
I will freely admit I know next to nothing about the VR support. I will let others chime in though, if they think this is feasible. @swlegion/core?

**Comment by aldaranmoses** [comment]
is this an actual problem with the range ruler it self or specifically a problem in VR?

**Comment by matanlurey** [comment]
@g-doh?

**Comment by g-doh** [comment]
ow sorry. tough day ... tough week actually. 

so the range ruler is actually a big wish because it is only usable in VR. There is no 15 degrees minimum rotation when you are holding an object and using it as the range ruler. If i'm not mistaken you are always allowed to use the range ruler to measure in advance from an enemy unit right?

so now that is not possible since the range circles come only from the leader that has been activated. I cannot those circles to pre measure in spots where I might move my unit.

now the movement tool is a different matter. that thing is completely unusable in VR. it comes apart as soon as you "grab" it in VR. I can only make straight moves using the tool. and I can of course move the figures by hand but without the movement tool that would be based on an range estimate.

the simplest way to fix it might be to put 3 movement tools in the game that consists of 2 parts and make it obvious where you should let those parts overlap
![20190920222817_1](https://user-images.githubusercontent.com/55522963/65357390-3ab73100-dbf7-11e9-910f-a2f9a52da2bf.jpg)
![20190920222820_1](https://user-images.githubusercontent.com/55522963/65357393-3c80f480-dbf7-11e9-91a4-e7c5f142d28a.jpg)
![20190920222826_1](https://user-images.githubusercontent.com/55522963/65357409-486cb680-dbf7-11e9-8fea-62ce22103fe5.jpg)

**Comment by matanlurey** [comment]
Thanks that is pretty detailed!
