### ISSUE TITLE
Linting / Style guide for LUA code

### ISSUE THREAD

**Issue by RyanMG** [swlegion/tts#50]
**Is your feature request related to a problem? Please describe.**
Code needs visual and stylistic constancy throughout.  A defined project style guide, as well as auto-linting, will go a long way towards helping us achieve that. 

**Describe the solution you'd like**
Research and present linting options to the development leads for approval. On approval 
1) implement linting system into codebase
2) Document how to set up linters in the IDE
3) Develop a styleguide outlining current best practices.

**Comment by RyanMG** [comment]
Starting progress 9/20/29

**Comment by matanlurey** [comment]
Style guide complete: https://github.com/swlegion/tts/wiki/Lua-Style-Guide.

@RyanMG to still investigate linting, IDE support, potential CI support.

**Comment by matanlurey** [comment]
@RyanMG Still planning to work on this?
