### ISSUE TITLE
Move assets from Tierens desktop to this GitHub

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#52]
![](https://user-images.githubusercontent.com/168174/65377947-b43a3800-dc66-11e9-9cb0-23f3e3269153.png)

... should likely all go in an `asset` folder, i.e. `mod/asset`.

**Comment by aldaranmoses** [comment]
There are possibly multiple 3D mesh files for a single model, which when exported create a single mesh file for a model (I am guessing based on what I saw on tierens video). 

Should we only keep the final exported asset used in the mod?

**Comment by aldaranmoses** [comment]
For card decks you create a single image file containing a grid of card images, do we want the individual  card images on github or just the final image for uploading?

**Comment by matanlurey** [comment]
> Should we only keep the final exported asset used in the mod?

That makes the most sense for me.

> Do we want the individual card images on GitHub?

Is the single grid of cards often changed, like, are more cards added? If so, we should probably upload the grid. If not, we can upload the individual cards. We could also always have some scripts that create grid images for us.

**Comment by aldaranmoses** [comment]
I discovered imagemagick, a command line tool that can "montage" the images into a grid, this makes generating the deck image a breeze. Having all the individual images would be best to enable the re-generation of decks.
