### ISSUE TITLE
Updated HD Scans of Cards

### ISSUE THREAD

**Issue by Krispe157** [swlegion/tts#533]
**Is your feature request related to a problem? Please describe.**
Reading a lot of these cards really really hurts my eyes. The best scan I've seen so far is of the Droid Commandos (Strike Team), everything else I've seen has been incredibly blurry.

**Describe the solution you'd like**
Better scans to make the cards more readable.

**Describe alternatives you've considered**
I haven't found any suitable replacements.

**Additional context**
This isn't the end of the world for me, it's not like it makes the mod unplayable, it just makes it really frustrating and sometimes headache inducing. The mod is amazing, but this is really hurting it for me.

**Comment by matanlurey** [comment]
We accept contributions, otherwise we don't track issues about individual asset updates.
