### ISSUE TITLE
Make map contributions separate from the mod itself?

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#54]
_FYI: The proposal is not to do any of this until the conclusion of IL4._

Right now, there are several categories of maps bundled with the mod:

* Learning Game
* Maps
  * Pre-Made Maps
    * Standard Maps
    * Tournament Maps
    * Random Tournament Map
    * Gathering Legions Maps
    * Battle Lines Maps
    * User Made Maps
  * Competitive Terrain Map

I'm proposing we cut the scope of what is offered as part of the mod significantly, in order to decouple updating maps or fixing broken links in maps from the mod itself (especially now that we will have more than 1 person contributing):

## Learning Game

Keep It. 

(We need to fix some broken textures BTW)

## Standard Maps

Keep a few? I think it is nice to have 3-5 maps that we think will not need to updated often (they do not have to be hyper competitive, for example), so that the mod is very usable out of the box.

I would remove the rest, however.

## Tournament Maps

I would remove all of these, as they seem to change the most often, and the actual mod development team seems not to be involved in the map development. 

I'd like to look into having a separate mod channel (on the Steam Workshop) for this purpose, i.e. subscribing to "Star Wars Legion Tournament Maps" would give you access to a bunch of different maps/cartridges. 

## Gathering Legion Maps

I would remove all of these. This is no longer actively maintained/developed.

## Battle Lines Maps

I would remove all of these. Some of them do not work, for example.

## User Made Maps

I would remove all of these, they seem very suited for separate workshop items that users can contribute. We could even keep a Wiki page of popular maps and workshop items.

## Competitive Terrain Map

Keep It.

I do not know how often these are updated, so maybe it just makes sense to keep them as-is for now and consider decoupling them if and only if they end up needing a lot of updates and additions in in the future.

**Comment by aldaranmoses** [comment]
having a map mod for each tournament containing the map objects and use additive load to load into the mod

**Comment by aldaranmoses** [comment]
After discussion the plan is:

To remove the majority of the maps to their own mods, we will survey the community on which maps to keep in the mod. The mod already has the Data Disk Mount (which is used to load maps from the Data Cartridges) visible next to the Game Controller, making this a really easy change as the functionality is already there.

To load a map the user subscribes to a map mod, after loading the SWL mod, opens the Games menu, finds the desired mod under the workshop list and selects Expand from the menu. This opens a panel with a list of objects (Data Cartridges in this case) in the mod then clicking the required item will spawn it into the existing game. Then the user places that cartridge on the mount and uses the Map menu on the Game Controller to load the map.

I suggest we contact the owners of the map groups to see if they will manage their respective map mod, if they decline then we will take ownership with a disclaimer that we are not responsible for the content.

We will also create a "template" source map mod containing the tools to create new maps.

**Comment by matanlurey** [comment]
I think we agreed to postpone this to mod 2.0.
