### ISSUE TITLE
Add google analytics to the mod

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#55]
Right now, @tieren31 has a very basic tracking script:

```lua
function updateModLoad()
    WebRequest.get("https://tierenswlegion.firebaseio.com/modLoadCount.json", self, "readCallback")
end

function readCallback(req)
    if req.is_done and not req.is_error then
        local currNum = tonumber(req.text)
        if currNum then
            WebRequest.put('https://tierenswlegion.firebaseio.com/modLoadCount.json', tostring(currNum+1), self, 'dummy')
        end
    end
end
```

We should consider using [Google Analytics][], since it's (a) free, (b) can be shared with multiple people, and (c) is going to have lot more relevant information/views that could be insightful.

[Google Analytics]: https://analytics.google.com/analytics/web/

**Comment by aldaranmoses** [comment]
What kind of metrics do want to measure?

**Comment by matanlurey** [comment]
@aldaranmoses: A few things:

* 30 Day Actives (Unique Users)
* Average time in session

We could also track some other interesting meta information

* Most played maps
* Most played units/upgrades/lists/factions

**Comment by matanlurey** [comment]
I think we agreed to postpone this to mod 2.0.
