### ISSUE TITLE
Cohesion bubbles on trooper units are too large, by about quarter of an inch

### ISSUE THREAD

**Issue by TheTwish** [swlegion/tts#56]
**Describe the bug**
Cohesion bubbles on trooper units are too large, by about half/quarter of an inch. As when you pull up the speed 1 template it does not reach minis that are at the edge of the bubble

**To Reproduce**
Open cohesion bubble on a trooper unit, only tested on basic rebel trooper with no upgrades thus far

**Expected behavior**
Should be about quarter of an inch smaller

**Screenshots**
![image](https://user-images.githubusercontent.com/55704668/65437185-43884c80-de1b-11e9-8316-9b7e26d37548.png)
Picture also in TTS chat in case that one doesn't work

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
[](url)

**Comment by matanlurey** [comment]
Thanks @TheTwish!

**Comment by Col-Ki** [comment]
I'd always had a sneaky feeling that cohesion in TTS was very generous, but never actually tested it!

This seems related to the cohesion bubble issue for notched bases, in that the radius of the bubble seems to be calculated as 1.5*base + length of speed one tool, without allowing for the concave curvature at the ends of the tool or notch depth.

**Comment by matanlurey** [comment]
I believe this is fixed!

**Comment by Col-Ki** [comment]
I'm sorry Matan, it's not. I checked in both the main and test mod - this issue affects all units.
![Cohesion1](https://user-images.githubusercontent.com/55502065/78897041-21e36f80-7aa4-11ea-8fd1-a901e37bb5a4.png)
![Cohesion2](https://user-images.githubusercontent.com/55502065/78897048-2445c980-7aa4-11ea-8392-89b0c1ee5a77.png)
![Cohesion3](https://user-images.githubusercontent.com/55502065/78897057-26a82380-7aa4-11ea-95cd-24f553fcb0fc.png)
![Cohesion4](https://user-images.githubusercontent.com/55502065/78897065-2a3baa80-7aa4-11ea-9ae9-d61d898d884e.png)

**Comment by matanlurey** [comment]
I agree! Reopening
