### ISSUE TITLE
Consider unactivated minis to auto-lock on the table

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#60]
... until they are activated, locking again after activation.

Sort of a variant on https://github.com/swlegion/tts/issues/45.

I am a little paranoid about implementing this, since it seems like a very easy bug vector to accidentally have units locked/unlocked when they are supposed to be the other state. Apparently though, the Armada mod does this just fine (admittedly they have less fiddling than Legion).

If we decide to go through with this, it might make sense to add this behind a feature flag/option that is conditionally enabled, so that if the feature is buggy or not completely tested yet it doesn't impact normal play.

We might also want to answer some obvious questions, like, how force push is expected to interact (do you activate the opposing unit, for example), how you remove minis from the opposing unit, etc.

**Comment by nashjaee** [comment]
This is how I envision this feature working:

1. At the beginning of the game, all minis on the table are locked (maybe this is done as each unit is deployed).
2. Any time a unit is activated by a command token, all minis in that unit are unlocked.
3. Anytime the "Next" or "End" button on a command token is clicked, all minis in the unit associated with that token are locked.
4. In the case of the "Next" button, the current unit's minis are locked and the next unit's minis are immediately unlocked.

I think this should cover any issues related to Force Push, and players would essentially operate the same way they do right now. Grab one of your opponent's command tokens of the appropriate type and activate the unit you are pushing.

**Comment by matanlurey** [comment]
I think the only area that sort of sucks is attacking a unit, but we could also make the unit that is a target of an attack auto-unlock.
