### ISSUE TITLE
C3PO is sometimes treated as the unit leader

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#62]
**Describe the bug**
The way C3PO is implemented for the R2-D2 unit is not consistent with how the card is actually played. C3PO is implemented as a separate unit card (and as a result, mini), where in practice he is more like a medical droid personnel upgrade to an existing squad.

As a result:

* C3PO responds as a unit leader for an Operative Token (he should not).
* R2D2 is not considered a unit with multiple minis (he should be, in this case).

**To Reproduce**
Create a Rebel list. Add R2-D2 and C3-PO. Spawn minis.

**Screenshots**
![](https://user-images.githubusercontent.com/168174/65560499-d09ed480-def3-11e9-9d9f-1eae4554ec44.png)

---

Fixing this might be a little more complicated, because `Counterpart` essentially is a new rule that sort of blends a personnel-type upgrade with a unit that is otherwise a single miniature (nothing else exists like this to my knowledge).

For example, here is how they are encoded:

```lua
    unitInfo.c3po = {}
    unitInfo.c3po.commandType = "rebelOperative"
    unitInfo.c3po.baseSize = "small"
    unitInfo.c3po.fixedMove = false
    unitInfo.c3po.selectedSpeed = 1
    unitInfo.c3po.fixedArc = false
    unitInfo.c3po.squadStatus = false
    unitInfo.c3po.buttonHeight = 2
    unitInfo.c3po.noToken = true

    unitInfo.r2d2 = {}
    unitInfo.r2d2.commandType = "rebelOperative"
    unitInfo.r2d2.baseSize = "small"
    unitInfo.r2d2.fixedMove = false
    unitInfo.r2d2.selectedSpeed = 1
    unitInfo.r2d2.fixedArc = false
    unitInfo.r2d2.squadStatus = false
    unitInfo.r2d2.buttonHeight = 2

    unitInfo.republicC3po = {}
    unitInfo.republicC3po.commandType = "republicOperative"
    unitInfo.republicC3po.baseSize = "small"
    unitInfo.republicC3po.fixedMove = false
    unitInfo.republicC3po.selectedSpeed = 1
    unitInfo.republicC3po.fixedArc = false
    unitInfo.republicC3po.squadStatus = false
    unitInfo.republicC3po.buttonHeight = 2
    unitInfo.republicC3po.noToken = true

    unitInfo.republicR2d2 = {}
    unitInfo.republicR2d2.commandType = "republicOperative"
    unitInfo.republicR2d2.baseSize = "small"
    unitInfo.republicR2d2.fixedMove = false
    unitInfo.republicR2d2.selectedSpeed = 1
    unitInfo.republicR2d2.fixedArc = false
    unitInfo.republicR2d2.squadStatus = false
    unitInfo.republicR2d2.buttonHeight = 2
```

_Probably_, it makes sense to have R2 as `squadStatus` = true, and remove (?) the .commandType of C3PO - I am not sure how that is handled right now, but perhaps `= nil` will be enough. I can experiment a bit.

**Comment by nashjaee** [comment]
Can the value of `squadStatus` be set when the list is spawned? At that time, you can check if C3PO exists in the list to determine if it needs to be true/false.

**Comment by matanlurey** [comment]
I think in practice it could be. Whether or not that is worth doing is another question (it adds another logic gate that ultimately the only effect is spawning a cohesion bubble, I think?)

**Comment by matanlurey** [comment]
Changes made (to both the Rebel and GAR versions):

```lua
- .r2D2.squadStatus = false
+ .r2D2.squadStatus = true
```

```lua
- .c3po.commandType = '... Operative'
+ .c3po.commandType = nil
```

```lua
.unitCards.republicC3po = {
  - tokenName = "Republic Operative Command Token",
  + tokenName = ""
  - rank = "Operative"
  + rank = "Counterpart"
}
```
