### ISSUE TITLE
Recover all green tokens button at the end of the round doesn't remove smokes

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#76]
originally mentioned in chat by Azeron Bloodmoone#5795

**Describe the bug**
recover all tokens button at the end of the round doesn't remove smokes

**To Reproduce**
1. Click Return Tokens
2. Smoke tokens remain on the battlefield
3. All other tokens are removed

**Expected behavior**
Smoke tokens should be removed from the battlefield

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by matanlurey** [comment]
Looks easy, thanks for filing!
