### ISSUE TITLE
Movement tool spawns incorrectly when cycling between unit types with different base configurations

### ISSUE THREAD

**Issue by RyanMG** [swlegion/tts#83]
**Describe the bug**
When cycling through units of the same type with different base sizes, the code does not alter its data about the base and its setup from whatever the FIRST unit selected is.
So if you activate a shoretrooper unit, then use the NEXT button to select a mortar unit, and try to move said unit, it will use the shoretroopers base size and movement speed for the mortar.
In the opposite, if you activate the mortar first, NEXT to the shore trooper and activate it, then move, you will see the shore trooper spawn with a speed 1 notched tool and arc indicators.

**To Reproduce**
1. Spawn a shore trooper unit and a mortar trooper unit
2. Pull a corp token and set it next to the shore trooper unit. Activate this unit.
3. Hit NEXT to select the mortar.
4. Select MOVE to spawn movement tools. Note that the mortar spawns a speed 2 tool which is not locked to the notch. Note that no arcs are marked in the range bands.
5. END the activation. Move the token to the mortar trooper and activate it.
6. Hit NEXT to select the shoretrooper
7. Select MOVE to spawn movement tools. Note that the speed 1 movement tool is spawned, and it is not pushed up against the base of the mini.
7. Select RANGE. Note that arc indicators spawn for this mini, and that the range bands are larger than they should be.

**Expected behavior**
Cycling through units should respect each units base data when activating.

**Comment by nashjaee** [comment]
Reopening this as it appears the fix wasn't actually applied, and the issue still exists.
