### ISSUE TITLE
Army List Importer

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#86]
**Is your feature request related to a problem? Please describe.**

The ability to take a list from an army list builder e.g. Tabletop Admiral, paste it in to the mod and generate the cards and mini's.

**Describe the solution you'd like**

The best format for this would be a json string as then the mod does not need to interpret each list builders list structure, this would of course require the list builders to be persuaded to add a json export.

Then using an XML UI InputField the user can paste the json string and generate the army's cards and mini's or even a data disk that could be saved.

We would need to define the json schema for the ALB's.

**Describe alternatives you've considered**
Adding a parser for each ALB, but that would lead to the mod requiring updates if the ALB changes their output or needing to add a new ALB.

**Comment by aldaranmoses** [comment]
The developers of tabletopadmiral.com and legion-hq.com have indicated they are willing to make lists available in json for the mod.

**Comment by aldaranmoses** [comment]
lets define the required json schema and pass it on to the ALB's

**Comment by aldaranmoses** [comment]
Do you think we need to restructure the unitInfo and cardInfo for this to work?

**Comment by nashjaee** [comment]
I've been looking into this feature over the past couple days. I propose the following JSON schema for sharing list data:

```json
{
  "pts": { "type": "integer" },
  "armyFaction": {
    "type": "string",
    "pattern": "^rebel|imperial|separatist|republic$"
  },
  "commandCards": {
    "type": "array",
    "items": { "type": "string" }
  },
  "units": {
    "type": "object",
    "properties": {
      "unitName": { "type": "string" },
      "upgrades": { "type": "array", "items": { "type": "string" } }
    }
  },
  "battlefieldDeck": {
    "type": "object",
    "properties": {
      "conditions": { "type": "array", "items": { "type": "string" }, "minItems": 4, "maxItems": 4 },
      "deployment": { "type": "array", "items": { "type": "string" }, "minItems": 4, "maxItems": 4 },
      "objective": { "type": "array", "items": { "type": "string" }, "minItems": 4, "maxItems": 4 }
    }
  }
}
```

Additionally, one of the larger issues we have to address on our end in the mod is resolving our reliance on `varName` in the list spawner. The simplest solution I can think of is to write a method inside the list builder that translates `unitName` into `varName`, using `cardInfo.unitCards` as the go-between since it seems all the data is in that table.

**Comment by nashjaee** [comment]
![importFromBuilder](https://user-images.githubusercontent.com/8440699/103159384-b5b5b280-477d-11eb-9c7f-f2e88c0d362b.jpg)

As for interface, a simple button and text input field in the list builder's XmlUI should suffice.

**Comment by matanlurey** [comment]
I'm marking this closed!
