### ISSUE TITLE
Order Tokens - The activate button is blank

### ISSUE THREAD

**Issue by aldaranmoses** [swlegion/tts#93]
**Describe the bug**
When drawing an order token from the stack the activate button has no label and requires clicking twice to active the button, the first click displays the label, the 2nd then activates the token.

**To Reproduce**

1. Draw a token from the command stack
2. The button outline is there, but no label
3. Click the button once and the label appears
4. Click again to activate and the token expands as expected

**Expected behavior**
The token button should have a label and only require a single click to activate

**Screenshots**
![Order Token Button Not Labeled](https://user-images.githubusercontent.com/53875637/66465699-a1569e80-ea81-11e9-832a-93df0dcf3908.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by matanlurey** [comment]
This was fixed by @RyanMG in #99. Thanks @RyanMG!
